### ISSUE TITLE
can't run on google colab

### ISSUE THREAD

**Issue by sugizo** [magv/bchess#1]
**steps**
```
pip install -U bchess 
!bchess

```
**result**
```
Traceback (most recent call last):
  File "/usr/local/bin/bchess", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/bchess/bchess.py", line 640, in main
    curses.wrapper(curses_main)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/bchess/bchess.py", line 619, in curses_main
    curses.curs_set(False)
_curses.error: curs_set() returned ERR
```

**expected result**
can run on google colab

**Comment by magv** [comment]
I don't know what google colab is, but a quick search tells me it's a Jupyter notebook service? This program needs an interactive terminal, so Jupyter notebooks won't work.
